name: Run Playwright & Deploy Allure Report

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers and Dependencies
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Generate Allure Report
        run: |
          pnpm exec allure generate allure-results --clean -o allure-report
          touch allure-report/.nojekyll

      - name: Set date variable (UTC+7, format dd-MM-yyyy_HH-mm-ss)
        id: date
        run: |
          DATE=$(TZ=Asia/Bangkok date +'%d-%m-%Y_%H-%M-%S')
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Checkout 'report' branch
        uses: actions/checkout@v4
        with:
          ref: report
          path: report-branch

      - name: Copy report to timestamped folder
        run: |
          mkdir -p report-branch/run-${{ steps.date.outputs.date }}
          cp -r allure-report/* report-branch/run-${{ steps.date.outputs.date }}

      - name: Update index.html with script
        run: |
          cd report-branch
          bash ../scripts/index-allure-report.sh

      - name: Deploy to GitHub Pages (branch 'report')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report-branch
          publish_branch: report
