name: Run Playwright & Deploy Allure Report

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers and Dependencies
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Generate Allure Report
        run: |
          pnpm exec allure generate allure-results --clean -o allure-report
          touch allure-report/.nojekyll

      - name: Set date variable (UTC+7, format dd-MM-yyyy_HH-mm-ss)
        id: date
        run: |
          DATE=$(TZ=Asia/Bangkok date +'%d-%m-%Y_%H-%M-%S')
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Checkout 'report' branch
        uses: actions/checkout@v4
        with:
          ref: report
          path: report-branch

      - name: Copy report to timestamped folder
        run: |
          mkdir -p report-branch/run-${{ steps.date.outputs.date }}
          cp -r allure-report/* report-branch/run-${{ steps.date.outputs.date }}

      - name: Update index.html to include all runs with styled CSS and header aligned with list
        run: |
          cd report-branch
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Allure Reports Archive</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
                  Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
                background-color: #f7f9fc;
                color: #333;
                margin: 2rem;
                display: flex;
                flex-direction: column;
                align-items: center;
              }
              h1 {
                color: #2e85ff;
                margin-bottom: 1rem;
                font-weight: 700;
                font-size: 1.8rem;
                white-space: nowrap;
              }
              ul {
                list-style: none;
                padding: 0;
                margin: 0;
                width: 300px;
              }
              li {
                background: white;
                border-radius: 6px;
                box-shadow: 0 2px 5px rgb(0 0 0 / 0.1);
                margin-bottom: 0.5rem;
                transition: box-shadow 0.3s ease;
              }
              li:hover {
                box-shadow: 0 4px 12px rgb(46 133 255 / 0.4);
              }
              a {
                display: block;
                padding: 0.75rem 1rem;
                text-decoration: none;
                color: #2e85ff;
                font-weight: 600;
                font-size: 1.1rem;
                white-space: nowrap;
              }
              a:hover {
                background-color: #e6f0ff;
              }
            </style>
          </head>
          <body>
            <h1>Allure Reports Archive</h1>
            <ul>
          EOF

          for d in $(ls -d run-* | sort -r); do
            echo "              <li><a href=\"${d}/index.html\">${d}</a></li>" >> index.html
          done

          cat >> index.html << 'EOF'
            </ul>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages (branch 'report')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report-branch
          publish_branch: report
