name: Run Playwright & Deploy Allure Report

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers and Dependencies
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Generate Allure Report
        run: |
          pnpm exec allure generate allure-results --clean -o allure-report
          touch allure-report/.nojekyll

      - name: Set date variable (UTC+7)
        id: date
        run: |
          # ตั้ง timezone เป็น Asia/Bangkok (UTC+7)
          DATE=$(TZ=Asia/Bangkok date +'%Y-%m-%d-%H%M%S')
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Checkout 'report' branch
        uses: actions/checkout@v4
        with:
          ref: report
          path: report-branch

      - name: Copy report to timestamped folder
        run: |
          mkdir -p report-branch/run-${{ steps.date.outputs.date }}
          cp -r allure-report/* report-branch/run-${{ steps.date.outputs.date }}

      - name: Update index.html to include all runs
        run: |
          cd report-branch
          # เริ่มเขียน index.html ใหม่ (เก็บ header)
          echo "<html><body><h1>Allure Reports</h1><ul>" > index.html

          # ลิสต์โฟลเดอร์ run-* และเรียงย้อนเวลาล่าสุดก่อน
          for d in $(ls -d run-* | sort -r); do
            echo "<li><a href=\"${d}/index.html\">${d}</a></li>" >> index.html
          done

          echo "</ul></body></html>" >> index.html

      - name: Deploy to GitHub Pages (branch 'report')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report-branch
          publish_branch: report
